Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2021-03, with the labels that each got.

#168 Added RHEL 8 and fixed postgresql service name
  docs/README.md
  docs/deployment-guide.md
Labels: PR: reviewed-approved

#172 move selinux config to appropriate roles
  roles/adw/tasks/nginx.yml
  roles/nginx/tasks/main.yml
Labels: PR: reviewed-approved

#169 OPSEXP-818: revisit the way services are handled
  roles/activemq/handlers/main.yml
  roles/activemq/molecule/default/molecule.yml
  roles/activemq/tasks/main.yml
  roles/adw/handlers/main.yml
  roles/adw/tasks/nginx.yml
  roles/nginx/handlers/main.yml
  roles/nginx/tasks/main.yml
  roles/nginx/tasks/vhosts.yml
  roles/postgres/handlers/main.yml
  roles/repository/handlers/main.yml
  roles/repository/tasks/main.yml
  roles/search/handlers/main.yml
  roles/search/molecule/default/molecule.yml
  roles/search/tasks/main.yml
  roles/sfs/handlers/main.yml
  roles/sfs/molecule/default/molecule.yml
  roles/sfs/tasks/main.yml
  roles/sync/handlers/main.yml
  roles/sync/tasks/main.yml
  roles/tomcat/handlers/main.yml
  roles/tomcat/molecule/default/converge.yml
  roles/tomcat/molecule/default/molecule.yml
  roles/tomcat/tasks/main.yml
  roles/transformers/handlers/main.yml
  roles/transformers/molecule/default/converge.yml
  roles/transformers/molecule/default/molecule.yml
  roles/transformers/tasks/main.yml
  roles/trouter/handlers/main.yml
  roles/trouter/molecule/default/converge.yml
  roles/trouter/molecule/default/molecule.yml
  roles/trouter/tasks/main.yml
Labels: PR: unreviewed

#175 OPSEXP-846: Update ansible
  .travis.yml
  docs/README.md
  docs/deployment-guide.md
  docs/generate-target-hosts.md
Labels: PR: partially-approved

#176 OPSEXP-849: Update generated README.txt to point to official docs rather than GitHub
  scripts/generate-zip.sh
Labels: PR: reviewed-approved

#174 OPSEXP-847: Change base URL's for Nexus
  community-extra-vars.yml
  group_vars/all.yml
  roles/repository/molecule/default/converge.yml
  tests/test-extra-vars.yml
Labels: PR: partially-approved

#177 OPSEXP-848: Only include os vars if the files actually exist
  roles/adw/templates/nginx.repo
  roles/common/tasks/main.yml
  roles/nginx/templates/nginx.repo
  roles/postgres/tasks/main.yml
  roles/postgres/vars/CentOS8.yml
  roles/postgres/vars/RedHat8.yml
  roles/repository/tasks/main.yml
  roles/sync/tasks/main.yml
  roles/transformers/tasks/main.yml
Labels: PR: unreviewed
