Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2021-04, with the labels that each got.

#179 OPSEXP-834 release anywhere in the commit message
  .travis.yml
Labels: PR: reviewed-approved

#178 Opsexp 850
  .travis.yml
  docs/deployment-guide.md
  group_vars/all.yml
  roles/nginx/tasks/vhosts.yml
  roles/nginx/vars/main.yml
  roles/nginx/vars/ssl.yml
  roles/repository/templates/share-config-custom.xml
  roles/tomcat/templates/server.xml
  tests/create_ansible-test.trial-dev.alfresco.me.yaml
  tests/delete_ansible-test.trial-dev.alfresco.me.yaml
  tests/test-ssl.yml
Labels: PR: unreviewed

#180 OPSEXP-813: Firewalld issues on clean machines
  .travis.yml
  docs/deployment-guide.md
  playbooks/acs.yml
  playbooks/prerequisite_checks.yml
  roles/helper_modules/library/listen_port.py
  roles/helper_modules/tasks/check_port.yml
Labels: PR: unreviewed

#181 OPSEXP-865: port defatultvars
  .travis.yml
  playbooks/prerequisite_checks.yml
  roles/common/defaults/main.yml
  roles/helper_modules/tasks/check_port.yml
  roles/nginx/templates/alfresco.conf
  roles/repository/handlers/main.yml
  roles/repository/tasks/main.yml
  roles/repository/templates/alfresco-global.properties
  roles/repository/vars/main.yml
  roles/repository/vars/postgres.yml
  roles/search/templates/solrcore.properties
  roles/sync/handlers/main.yml
  roles/sync/tasks/main.yml
  roles/sync/templates/config.yml.j2
  roles/sync/vars/postgres.yml
  roles/tomcat/templates/server.xml
  roles/transformers/handlers/main.yml
  roles/transformers/templates/ats-ate-aio.sh
  roles/trouter/handlers/main.yml
  roles/trouter/templates/ats-atr.sh
Labels: PR: unreviewed

#183 OPSEXP-809: Upgrade DTAS usage to v1.0
  .travis.yml
  tests/test-config-acs6-stack.json
  tests/test-config-community.json
  tests/test-config.json
Labels: PR: reviewed-approved

#186 OPSEXP-882: Added proxy related quick fixes in the Communication Failures section
  docs/deployment-guide.md
Labels: PR: partially-approved

#185 OPSEXP-886 do not rely on releasever as its behaviour varies
  roles/transformers/tasks/main.yml
Labels: PR: reviewed-approved

#184 OPSEXP-881 Use ansible (local) lookups to prevent side effects of become tasks
  roles/common/defaults/main.yml
  roles/common/tasks/main.yml
  roles/postgres/tasks/main.yml
  roles/repository/tasks/main.yml
  roles/sync/tasks/main.yml
  roles/sync/vars/CentOS8.yml
  roles/sync/vars/RedHat.yml
  roles/sync/vars/RedHat7.yml
  roles/sync/vars/RedHat8.yml
  roles/transformers/tasks/main.yml
Labels: PR: partially-approved
