Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2022-11, with the labels that each got.

#490 pin pipenv to 2022.10.12
  .github/actions/pipenv/action.yml
Labels: PR: unreviewed

#491 OPSEXP-1803 Add Search Enteprise reindex service
  .ansible-lint
  .github/workflows/enteprise.yml
  .pre-commit-config.yaml
  docs/deployment-guide.md
  molecule/elasticsearch/molecule.yml
  molecule/elasticsearch/verify.yml
  molecule/multimachine/prepare.yml
  playbooks/acs.yml
  playbooks/prerequisite-checks.yml
  playbooks/search-enterprise-reindex.yml
  roles/common/defaults/main.yml
  roles/repository/templates/alfresco-global.properties.j2
  roles/search_enterprise/defaults/main.yml
  roles/search_enterprise/molecule/default/host_vars/search-ent-instance.yml
  roles/search_enterprise/molecule/default/verify.yml
  roles/search_enterprise/tasks/main.yml
  roles/search_enterprise/templates/elasticsearch-cfg.j2
  roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
  roles/search_enterprise/templates/elasticsearch-connector.service.j2
  roles/sync/templates/config.yml.j2
  roles/transformers/handlers/main.yml
  roles/transformers/templates/ats-ate-aio.sh.j2
  roles/trouter/templates/ats-atr.sh.j2
Labels: PR: partially-approved

#501 workaround for user admin in community
  roles/repository/templates/share-config-custom.xml.j2
Labels: PR: reviewed-approved

#499 OPSEXP-1795 Bump community extra vars for ACS 7.3
  .github/workflows/enteprise.yml
  community-extra-vars.yml
  docs/README.md
  roles/repository/molecule/default/host_vars/repository-instance.yml
  roles/repository/tasks/main.yml
  tests/test-config-community.json
Labels: PR: reviewed-approved

#500 OPSEXP-1835: support for java 17
  .secrets.baseline
  docs/deployment-guide.md
  group_vars/all.yml
  playbooks/acs.yml
  roles/java/tasks/main.yml
  roles/repository/defaults/main.yml
  roles/repository/molecule/default/host_vars/repository-instance.yml
  roles/search/defaults/main.yml
  roles/search/handlers/main.yml
  roles/search/molecule/default/converge.yml
  roles/search/tasks/main.yml
  roles/search/templates/solr.in.sh
  roles/search/vars/main.yml
  tests/test-7.1-vars.yml
Labels: PR: partially-approved

#506 OPSEXP-1833 Bump imagemagick package version
  6.2.N-extra-vars.yml
  7.0.N-extra-vars.yml
  7.1.N-extra-vars.yml
  7.2.N-extra-vars.yml
  group_vars/all.yml
  roles/transformers/vars/CentOS7.yml
  roles/transformers/vars/RedHat7.yml
  roles/transformers/vars/RedHat8.yml
  roles/transformers/vars/Rocky8.yml
  roles/transformers/vars/Ubuntu18.yml
  roles/transformers/vars/Ubuntu20.yml
  roles/transformers/vars/Ubuntu22.yml
  tests/test-7.1-vars.yml
Labels: PR: partially-approved

#508 OPSEXP-1829 Support search enterprise for ACS 7.1
  7.1.N-extra-vars.yml
  tests/test-7.1-vars.yml
Labels: PR: reviewed-approved

#509 OPSEXP-1795 Fixup release workflow
  .github/workflows/enteprise.yml
  scripts/generate-zip.sh
Labels: PR: reviewed-approved

#387 OPSEXP-1620 Update ACS versions via updatecli
  docs/developer-guide.md
  scripts/updatecli/updatecli_acs72.yml
  scripts/updatecli/updatecli_acs73.yml
  scripts/updatecli/updatecli_config.yml
Labels: PR: unreviewed
