Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2022-10, with the labels that each got.

#459 Hacktoberfest: deleted not defined port variable
  roles/common/defaults/main.yml
Labels: PR: reviewed-approved, hacktoberfest-accepted

#461 OPSEXP-1696 Add new workflow to mirror libreoffice on nexus
  .github/workflows/mirror-libreoffice.yml
Labels: PR: unreviewed

#460 OPSEXP-1755 Better cache handling for ansible galaxy
  .github/actions/galaxy/action.yml
Labels: PR: partially-approved

#463 OPSEXP-1756 Switch to nexus for libreoffice packages
  roles/transformers/tasks/main.yml
  roles/transformers/vars/main.yml
Labels: PR: reviewed-approved

#436 OPSEXP-1636 Add enteprise search role
  .github/workflows/enteprise.yml
  .pre-commit-config.yaml
  group_vars/all.yml
  inventory_ha.yml
  inventory_local.yml
  inventory_ssh.yml
  molecule/default/cleanup.yml
  molecule/default/prepare.yml
  molecule/default/verify.yml
  molecule/elasticsearch/converge.yml
  molecule/elasticsearch/host_vars/search-enteprise-integration-instance.yml
  molecule/elasticsearch/molecule.yml
  playbooks/acs.yml
  playbooks/check-versions.yml
  roles/common/defaults/main.yml
  roles/common/tasks/check_upgrades.yml
  roles/nginx/templates/alfresco.conf.j2
  roles/nginx/templates/alfresco_redirect.conf.j2
  roles/repository/templates/alfresco-global.properties.j2
  roles/search_enterprise/defaults/main.yml
  roles/search_enterprise/handlers/main.yml
  roles/search_enterprise/meta/main.yml
  roles/search_enterprise/molecule/default/converge.yml
  roles/search_enterprise/molecule/default/host_vars/search-ent-instance.yml
  roles/search_enterprise/molecule/default/molecule.yml
  roles/search_enterprise/molecule/default/verify.yml
  roles/search_enterprise/tasks/main.yml
  roles/search_enterprise/templates/elasticsearch-connector.service.j2
  roles/search_enterprise/vars/main.yml
Labels: PR: reviewed-approved

#465 OPSEXP-1755 Fixup missing roles in galaxy cache handling
  .github/actions/galaxy/action.yml
Labels: PR: reviewed-approved

#466 add prospector to dev packages
  Pipfile
  Pipfile.lock
Labels: PR: reviewed-approved

#467 Add version info in check versions playbook messages
  playbooks/check-versions.yml
Labels: PR: reviewed-approved

#470 OPSEXP-1753 Support variable artifacts name
  6.2.N-extra-vars.yml
  7.0.N-extra-vars.yml
  7.1.N-extra-vars.yml
  community-extra-vars.yml
  group_vars/all.yml
  roles/repository/tasks/main.yml
  roles/repository/vars/main.yml
  roles/search/tasks/main.yml
  roles/search_enterprise/tasks/main.yml
  roles/sfs/tasks/main.yml
  roles/transformers/tasks/main.yml
  roles/transformers/templates/ats-ate-aio.sh.j2
  roles/trouter/tasks/main.yml
  roles/trouter/templates/ats-atr.sh.j2
  tests/test-7.1-vars.yml
Labels: PR: reviewed-approved

#457 OPSEXP-1705 Disable installing ghostscript by default
  roles/repository/molecule/default/tests/test_repository.py
  roles/repository/vars/Debian.yml
  roles/transformers/defaults/main.yml
  roles/transformers/molecule/default/tests/test_transform.py
  roles/transformers/tasks/main.yml
  roles/transformers/vars/Debian.yml
  roles/transformers/vars/main.yml
  roles/trouter/molecule/default/tests/test_trouter.py
Labels: PR: reviewed-approved

#469 OPSEXP-1649 Fix uninstall playbook failure at clustered EC2 test
  molecule/multimachine/cleanup.yml
  playbooks/platform-uninstall.yml
Labels: PR: partially-approved

#471 OPSEXP-1740 Document the new search enterprise roles
  docs/README.md
  docs/deployment-guide.md
  docs/generate-target-hosts.md
Labels: PR: reviewed-approved

#474 OPSEXP-1762 Fix flaky elasticsearch integration tests
  .github/workflows/enteprise.yml
  playbooks/acs.yml
  roles/repository/defaults/main.yml
  roles/repository/templates/alfresco-content-monitored-startup.service.j2
  roles/sync/handlers/main.yml
  roles/sync/tasks/main.yml
Labels: PR: partially-approved

#479 OPSEXP-1772 Bump actions/cache in galaxy action
  .github/actions/galaxy/action.yml
Labels: PR: reviewed-approved

#477 OPSEXP-1770 Support for Ubuntu-22.04
  .github/workflows/enteprise.yml
  docs/README.md
  group_vars/all.yml
  molecule/default/vars-ubuntu22-community.yml
  roles/transformers/vars/Ubuntu22.yml
Labels: PR: partially-approved

#484 OPSEXP-1783 Fix mq broker creation when branch contains non-alphanumeric chars
  .github/workflows/enteprise.yml
  molecule/multimachine/cleanup.yml
  molecule/multimachine/prepare.yml
Labels: PR: unreviewed

#476 OPSEXP-1771 External elasticsearch cluster
  docs/deployment-guide.md
  inventory_ha.yml
  inventory_local.yml
  inventory_ssh.yml
  molecule/multimachine/prepare.yml
  playbooks/acs.yml
  playbooks/secrets-init.yml
  playbooks/secrets.yml
  roles/common/defaults/main.yml
  roles/repository/templates/alfresco-global.properties.j2
  roles/search_enterprise/molecule/default/converge.yml
  roles/search_enterprise/molecule/default/molecule.yml
  roles/search_enterprise/tasks/main.yml
  roles/search_enterprise/templates/elasticsearch-connector.service.j2
  tests/molecule/secrets.yml
Labels: PR: unreviewed

#485 OPSEXP-1742 Bump detect-secrets plugin
  .pre-commit-config.yaml
  .secrets.baseline
  group_vars/all.yml
  molecule/default/create.yml
  roles/activemq/molecule/default/tests/test_activemq.py
  roles/adw/tasks/main.yml
  roles/repository/tasks/main.yml
  roles/repository/templates/custom-slingshot-application-context.xml
  roles/search/tasks/main.yml
  roles/search/templates/solrcore.properties.j2
  roles/search_enterprise/tasks/main.yml
  roles/sfs/tasks/main.yml
  roles/sync/tasks/main.yml
  roles/transformers/tasks/main.yml
  roles/trouter/tasks/main.yml
  tests/molecule/secrets.yml
  tests/molecule_it/script.sh
Labels: PR: reviewed-approved

#489 OPSEXP-1813: fix wrong routing for alf-ES media cache url
  roles/search_enterprise/molecule/default/converge.yml
  roles/search_enterprise/molecule/default/verify.yml
  roles/search_enterprise/templates/elasticsearch-connector.service.j2
Labels: PR: partially-approved
