Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2022-04, with the labels that each got.

#303 [minor] fix md issues in components upgrade docs
  docs/components-upgrade.md
Labels: PR: reviewed-approved

#318 [minor] update prospector version
  .pre-commit-config.yaml
Labels: PR: unreviewed

#317 [minor] Add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .pre-commit-config.yaml
Labels: PR: reviewed-approved

#305 OPSEXP-1303 Document secrets present in the playbook
  docs/SECRETS.md
Labels: PR: partially-approved

#311 OPSEXP-1373 Use different users for different databases
  .github/workflows/community.yml
  group_vars/all.yml
  roles/postgres/molecule/default/converge.yml
  roles/postgres/molecule/default/molecule.yml
  roles/postgres/molecule/default/tests/test_postgres.py
  roles/postgres/tasks/main.yml
Labels: PR: reviewed-approved

#320 OPSEXP-1395: controlled usage of become within repo role
  docs/deployment-guide.md
  molecule/default/molecule.yml
  molecule/multimachine/molecule.yml
  playbooks/acs.yml
  roles/activemq/handlers/main.yml
  roles/activemq/molecule/default/host_vars/activemq-instance.yml
  roles/activemq/molecule/default/molecule.yml
  roles/activemq/molecule/default/tests/test_activemq.py
  roles/activemq/tasks/main.yml
  roles/common/molecule/default/host_vars/common-instance.yml
  roles/common/molecule/default/molecule.yml
  roles/common/tasks/main.yml
  roles/common/tasks/secrets.yml
  roles/java/molecule/default/host_vars/java-instance.yml
  roles/java/molecule/default/molecule.yml
  roles/java/molecule/default/tests/test_java.py
  roles/java/tasks/main.yml
  roles/postgres/defaults/main.yml
  roles/postgres/handlers/main.yml
  roles/postgres/molecule/default/host_vars/postgres-instance.yml
  roles/postgres/molecule/default/molecule.yml
  roles/postgres/molecule/default/tests/test_postgres.py
  roles/postgres/tasks/apt_repo.yml
  roles/postgres/tasks/dnf_repo.yml
  roles/postgres/tasks/main.yml
  roles/postgres/tasks/yum_repo.yml
  roles/postgres/vars/main.yml
  roles/repository/defaults/main.yml
  roles/repository/handlers/monitored-restart.yml
  roles/repository/molecule/default/host_vars/repository-instance.yml
  roles/repository/molecule/default/molecule.yml
  roles/repository/molecule/default/tests/test_repository.py
  roles/repository/tasks/main.yml
  roles/tomcat/handlers/main.yml
  roles/tomcat/molecule/default/converge.yml
  roles/tomcat/molecule/default/host_vars/tomcat-instance.yml
  roles/tomcat/molecule/default/molecule.yml
  roles/tomcat/molecule/default/tests/test_tomcat.py
  roles/tomcat/tasks/main.yml
  tests/molecule/Dockerfile-noprivs.j2
Labels: PR: reviewed-approved

#323 OPSEXP-1404: controled usage of become plugin in adw role
  roles/adw/defaults/main.yml
  roles/adw/handlers/main.yml
  roles/adw/molecule/default/host_vars/adw-instance.yml
  roles/adw/molecule/default/molecule.yml
  roles/adw/molecule/default/tests/test_adw.py
  roles/adw/tasks/main.yml
  roles/adw/tasks/nginx.yml
  roles/adw/templates/alfresco_adw.conf
  roles/adw/vars/main.yml
Labels: PR: reviewed-approved

#325 OPSEXP-1411 controled usage of become plugin in ansible search role
  playbooks/acs.yml
  roles/search/handlers/main.yml
  roles/search/molecule/default/host_vars/search-instance.yml
  roles/search/molecule/default/molecule.yml
  roles/search/molecule/default/tests/test_search.py
  roles/search/tasks/main.yml
Labels: PR: reviewed-approved

#326 OPSEXP-1416: controled usage of become plugin in ansible sync role
  playbooks/acs.yml
  roles/common/defaults/main.yml
  roles/sync/defaults/main.yml
  roles/sync/handlers/main.yml
  roles/sync/molecule/default/host_vars/syncservice-instance.yml
  roles/sync/molecule/default/molecule.yml
  roles/sync/molecule/default/tests/test_sync.py
  roles/sync/tasks/main.yml
Labels: PR: reviewed-approved

#332 OPSEXP-1310: bruteforce mitigation
  requirements.yml
  roles/repository/defaults/main.yml
  roles/repository/molecule/default/host_vars/repository-instance.yml
  roles/repository/molecule/default/tests/test_repository.py
  roles/repository/tasks/main.yml
  roles/repository/templates/alfresco-global.properties.j2
Labels: PR: reviewed-approved

#331 OPSEXP-1424: fix setenv.sh being wiped by subsequent roles' plays
  molecule/default/side_effects.yml
  playbooks/platform-restart.yml
  roles/java/tasks/main.yml
  roles/tomcat/tasks/main.yml
  tests/molecule_it/script.sh
Labels: PR: reviewed-approved
