Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2022-09, with the labels that each got.

#422 OPSEXP-1372 switch to FQN (part 4 - secrets-* playbooks, unifying name structure of playbooks)
  playbooks/prerequisite-checks.yml
  playbooks/secrets-init.yml
  playbooks/secrets.yml
Labels: PR: unreviewed

#426 OPSEXP:1716 update playbook name reference in documentation
  docs/deployment-guide.md
Labels: PR: reviewed-approved

#430 Improve integration tests docs
  docs/developer-guide.md
Labels: PR: reviewed-approved

#432 OPSEXP-1635 add elasticsearch role
  .github/workflows/community.yml
  requirements.yml
  roles/elasticsearch/defaults/main.yml
  roles/elasticsearch/handlers/main.yml
  roles/elasticsearch/meta/main.yml
  roles/elasticsearch/molecule/default/converge.yml
  roles/elasticsearch/molecule/default/host_vars/elasticsearch-instance.yml
  roles/elasticsearch/molecule/default/molecule.yml
  roles/elasticsearch/molecule/default/verify.yml
  roles/elasticsearch/tasks/main.yml
  roles/elasticsearch/vars/main.yml
Labels: PR: partially-approved

#448 OPSEXP-1736 allow better debugging experience of multimachine stage on local env
  .envrc
  .gitignore
  .pre-commit-config.yaml
  galaxy.yml
  group_vars/all.yml
  molecule/default/create.yml
  molecule/multimachine/cleanup.yml
  molecule/multimachine/hosts.yml
  molecule/multimachine/prepare.yml
  molecule/multimachine/templates/hosts.yml.j2
  roles/activemq/meta/main.yml
  roles/adw/meta/main.yml
  roles/common/meta/main.yml
  roles/elasticsearch/meta/main.yml
  roles/java/meta/main.yml
  roles/java/tasks/main.yml
  roles/nginx/meta/main.yml
  roles/nginx/tasks/vhosts.yml
  roles/postgres/meta/main.yml
  roles/repository/meta/main.yml
  roles/search/meta/main.yml
  roles/sfs/meta/main.yml
  roles/sync/meta/main.yml
  roles/tomcat/meta/main.yml
  roles/transformers/meta/main.yml
  roles/trouter/meta/main.yml
Labels: PR: unreviewed

#427 OPSEXP-1708: OS check prereqs
  docs/deployment-guide.md
  group_vars/all.yml
  playbooks/acs.yml
Labels: PR: reviewed-approved

#454 Opsexp 1293 imagemagick Imagemagick-7.1.0-16 version update
  roles/transformers/vars/CentOS7.yml
  roles/transformers/vars/RedHat7.yml
  roles/transformers/vars/RedHat8.yml
  roles/transformers/vars/Rocky8.yml
  roles/transformers/vars/Ubuntu18.yml
  roles/transformers/vars/Ubuntu20.yml
Labels: PR: reviewed-approved

#458 spell checks
  docs/README.md
  docs/components-upgrade.md
  docs/developer-guide.md
  docs/generate-target-hosts.md
  docs/playbook-upgrade.md
  scripts/generate-comp-ver-table.py
Labels: PR: reviewed-approved
