Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2022-03, with the labels that each got.

#251 OPSEXP-1250 avoid general failure with single failing checksum url
  .travis.yml
  community-extra-vars.yml
  group_vars/all.yml
  roles/activemq/tasks/main.yml
  roles/adw/tasks/main.yml
  roles/common/defaults/main.yml
  roles/common/vars/main.yml
  roles/repository/molecule/default/host_vars/repository1.yml
  roles/repository/tasks/main.yml
  roles/search/tasks/main.yml
  roles/sfs/tasks/main.yml
  roles/sync/tasks/main.yml
  roles/tomcat/tasks/main.yml
  roles/transformers/tasks/main.yml
  roles/transformers/vars/main.yml
  roles/trouter/tasks/main.yml
  tests/test-extra-vars.yml
Labels: PR: unreviewed

#275 OPSEXP-1297 Prospector configuration
  .pre-commit-config.yaml
  .prospector.yml
  .pylintrc
  roles/activemq/molecule/default/tests/test_activemq.py
  roles/adw/molecule/default/tests/test_adw.py
  roles/common/molecule/default/tests/test_common.py
  roles/helper_modules/library/listen_port.py
  roles/java/molecule/default/tests/test_java.py
  roles/nginx/molecule/default/tests/test_nginx.py
  roles/repository/molecule/default/tests/test_repository.py
  roles/search/molecule/default/tests/test_search.py
  roles/sfs/molecule/default/tests/test_sfs.py
  roles/sync/molecule/default/tests/test_sync.py
  roles/tomcat/molecule/default/tests/test_tomcat.py
  roles/transformers/molecule/default/tests/test_transform.py
  roles/trouter/molecule/default/tests/test_trouter.py
  scripts/generate-comp-ver-table.py
  scripts/lambda_cleanup/src/cleanup.py
Labels: PR: unreviewed

#243 OPSEXP-1217 retry molecule test on failure
  .travis.yml
  roles/postgres/handlers/main.yml
  roles/postgres/tasks/main.yml
  roles/repository/handlers/main.yml
  roles/repository/tasks/main.yml
  roles/sync/handlers/main.yml
  roles/transformers/tasks/main.yml
Labels: PR: reviewed-approved

#273 OPSEXP-1238 External ActiveMQ
  .ansible-lint
  docs/deployment-guide.md
  inventory_local.yml
  inventory_nfs.yml
  inventory_ssh.yml
  molecule/manual-activemq/README.md
  molecule/manual-activemq/hosts.yml
  molecule/manual-activemq/molecule.yml
  molecule/manual-activemq/vars.yml
  playbooks/acs.yml
  roles/activemq/molecule/default/molecule.yml
  roles/activemq/tasks/main.yml
  roles/common/defaults/main.yml
  roles/sync/molecule/default/molecule.yml
  roles/sync/templates/config.yml.j2
  roles/transformers/molecule/default/molecule.yml
  roles/trouter/molecule/default/molecule.yml
Labels: PR: reviewed-approved

#277 OPSEXP-1319 Fix random failure on async download repository task
  roles/repository/tasks/main.yml
Labels: PR: reviewed-approved

#269 OPSEXP-1237: Allow deploying repository and share cluster
  .pre-commit-config.yaml
  docs/deployment-guide.md
  docs/shared-contentstore.md
  inventory_ha.yml
  molecule/default/cleanup.yml
  molecule/multimachine/cleanup.yml
  molecule/multimachine/host_vars/repository_electron.yml
  molecule/multimachine/host_vars/repository_neutron.yml
  molecule/multimachine/host_vars/repository_proton.yml
  molecule/multimachine/molecule.yml
  molecule/multimachine/prepare.yml
  playbooks/acs.yml
  requirements.txt
  requirements.yml
  roles/common/defaults/main.yml
  roles/nginx/defaults/main.yml
  roles/nginx/molecule/default/molecule.yml
  roles/nginx/tasks/vhosts.yml
  roles/nginx/templates/alfresco.conf.j2
  roles/nginx/templates/alfresco_proxy.j2
  roles/nginx/templates/alfresco_redirect.conf
  roles/nginx/templates/alfresco_redirect.conf.j2
  roles/nginx/vars/main.yml
  roles/nginx/vars/ssl.yml
  roles/postgres/defaults/main.yml
  roles/postgres/templates/pg_hba.conf.j2
  roles/postgres/vars/main.yml
  roles/repository/defaults/main.yml
  roles/repository/handlers/main.yml
  roles/repository/handlers/monitored-restart.yml
  roles/repository/molecule/default/molecule.yml
  roles/repository/molecule/default/tests/test_repository.py
  roles/repository/tasks/main.yml
  roles/repository/tasks/sharedcs.yml
  roles/repository/templates/alfresco-global.properties
  roles/repository/templates/custom-slingshot-application-context.xml
  roles/repository/templates/share-config-custom.xml
  roles/repository/templates/share.xml
  roles/repository/vars/main.yml
  roles/search/tasks/main.yml
  roles/search/templates/solrcore.properties.j2
  roles/sync/handlers/main.yml
  roles/sync/molecule/default/converge.yml
  roles/sync/templates/config.yml.j2
  tests/test-config.json
  tests/test-extra-vars.yml
Labels: PR: unreviewed

#278 Bump tomcat to 9.0.59 due to CVE-2022-23181
  6.2.N-extra-vars.yml
  7.0.N-extra-vars.yml
  docs/README.md
  group_vars/all.yml
  roles/repository/tasks/main.yml
Labels: PR: partially-approved

#279 OPSEXP-1327 cluster rolling restarts
  roles/repository/handlers/main.yml
  roles/repository/tasks/main.yml
  roles/repository/templates/alfresco-content-monitored-startup.service.j2
  roles/repository/templates/alfresco-content-monitored-startup.sh.j2
  roles/tomcat/tasks/main.yml
Labels: PR: reviewed-approved

#281 Skip boto3 patch upgrades for dependabot
  .github/dependabot.yml
Labels: PR: partially-approved

#287 OPSEXP-1319 Test suggested workaround for unreliable libreoffice download
  roles/transformers/tasks/main.yml
Labels: PR: reviewed-approved

#289 Fix for jmespath conflict with boto3
  requirements.txt
Labels: PR: reviewed-approved

#290 [minor] Explicit order in versions table of README
  scripts/generate-comp-ver-table.py
Labels: PR: partially-approved

#288 OPSEXP-1222 migrate to github actions
  .github/actions/galaxy/action.yml
  .github/dependabot.yml
  .github/workflows/community.yml
  .github/workflows/contrib-sync.yml
  .github/workflows/contributions.yml
  .github/workflows/enteprise.yml
  .github/workflows/precommit.yml
  .github/workflows/release.yml
  .travis.yml
  VERSION
  molecule/default/prepare.yml
  molecule/default/verify.yml
  molecule/multimachine/prepare.yml
  scripts/generate-zip.sh
Labels: PR: reviewed-approved

#295 Minor fixes to inventories
  inventory_ha.yml
  inventory_ssh.yml
Labels: PR: reviewed-approved

#296 OPSEXP-1362: ensure external_groups precedence
  playbooks/acs.yml
Labels: PR: unreviewed

#293 OPSEXP-1328 Retry failing destroy during ec2 tests
  .github/workflows/enteprise.yml
  molecule/default/cleanup.yml
  molecule/multimachine/cleanup.yml
Labels: PR: reviewed-approved

#304 [minor] fix md issues in deployment guide docs
  docs/deployment-guide.md
Labels: PR: reviewed-approved

#306 [minor] Skip molecule tests for documentation PRs
  .github/workflows/community.yml
  .github/workflows/enteprise.yml
Labels: PR: reviewed-approved

#310 [minor] Ignore docs changes in community pull requests builds too
  .github/workflows/community.yml
  .github/workflows/enteprise.yml
Labels: PR: unreviewed
