Repository Alfresco/alfresco-ansible-deployment, pull requests merged in 2023-01, with the labels that each got.

#519 OPSEXP-1889 Drop support for ACS 6.2
  6.2.N-extra-vars.yml
  docs/README.md
  docs/deployment-guide.md
  tests/test-config-acs6-stack.json
Labels: PR: reviewed-approved

#464 Search replication
  .secrets.baseline
  docs/search-services-deployment-guide.md
  playbooks/acs.yml
  playbooks/search_replication.yml
  roles/search/defaults/main.yml
  roles/search/handlers/main.yml
  roles/search/meta/argument_specs.yml
  roles/search/molecule/default/converge.yml
  roles/search/molecule/default/molecule.yml
  roles/search/tasks/main.yml
  roles/search/tasks/replication.yml
  roles/search/templates/alfresco-search.service
  roles/search/templates/search_config_setup.sh
  roles/search/templates/solr.sh.j2
  roles/search/templates/solrcore.properties.j2
  roles/search/vars/main.yml
Labels: PR: reviewed-approved

#530 OPSEXP-1832 update imagemagick package
  7.0.N-extra-vars.yml
  7.1.N-extra-vars.yml
  7.2.N-extra-vars.yml
  group_vars/all.yml
Labels: PR: partially-approved

#531 OPSEXP-1936 Move quickstart at the start of deployment guide
  docs/deployment-guide.md
Labels: PR: unreviewed

#535 Fix missing pipenv run in ansible-vault docs
  docs/deployment-guide.md
Labels: PR: partially-approved

#538 Add Search enterprise component to the table
  docs/README.md
Labels: PR: reviewed-approved
